### PR TITLE
Spelling

### LINKED ISSUE #463: Spelling errors
### Describe the bug

There are a bunch of typos in the repository code...

### Reproduction

Apply https://github.com/jsoref/magidoc/commit/09da3748e49915a7f6c86aab86c1e7cf43c40968 and push (to a fork)

### Logs

```shell
https://github.com/jsoref/magidoc/actions/runs/23525216617/attempts/1#summary-68477087623
```

### System Info

```shell
(default)
```

### Severity

Annoyance

### PR DESCRIPTION
**Pull request by jsoref**
- Fixes #463

### CODE REVIEW

File: packages/cli/src/node/packageManager.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export async function selectPackageManager(): Promise<PackageManager> {
   }
 
   throw new Error(
-    `No Package Manager runner was found among on of the following: ${PACKAGE_MANAGER_TYPES.toString()}. Make sure that one of these is installed.`,
+    `No Package Manager runner was found among the following: ${PACKAGE_MANAGER_TYPES.toString()}. Make sure that one of these is installed.`,
```
Comment (jsoref) [inline packages/cli/src/node/packageManager.ts:46]: kinda notable

File: packages/plugins/rollup-plugin-gql-schema/tests/schema/query.spec.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ describe('fetching the graphql schema', () => {
           .reply(200, introspectionResult)
       })
 
-      it('uses the returns the introspection query result', async () => {
+      it('returns the introspection query result', async () => {
```
Comment (jsoref) [inline packages/plugins/rollup-plugin-gql-schema/tests/schema/query.spec.ts:36]: I'm not entirely certain about this (the old text is definitely poor, which makes it hard for me to be confident about my replacement)

File: packages/plugins/svelte-prismjs/src/lib/components/Prism.svelte [hunk 3]
```diff
@@ -78,7 +78,7 @@ $: {
     class="prism--code-container"
     style="--min-height: {minHeight}; --max-height: {maxHeight};"
     class:line-numbers={showLineNumbers}>
-    <code bind:this={root} />
+    <code bind:this={root}></code>
```
Comment (jsoref) [inline packages/plugins/svelte-prismjs/src/lib/components/Prism.svelte:81]: CI complained

**Review by pelletier197 — APPROVED** [review]
This seems alright. Thank you!
